package rules

import com.my.model.Address;
import com.my.model.AddressCheckResult;


function String hello(String name){
    return "Hello " + name + "!";
}

rule "myfunction.drl-1"
lock-on-active
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
    then
        System.out.println(hello("myfunction.drl-1"));
end

rule "2017myfunction.drl-2"
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
    then
        System.out.println(hello("2017myfunction.drl-2"));
end