package rules

import com.my.model.Address;
import com.my.model.AddressCheckResult;

global java.util.List myGlobalList;

rule "myrules.drl-1"
lock-on-active
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
         myGlobalList.add( Foo.hello("myrules.drl-1") );
        System.out.println("规则中打印日志：校验通过!");
end

rule "2017myrules.drl-2"
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
         myGlobalList.add( "2017myrules.drl-2" );
        System.out.println("规则中打印日志：校验通过2017!");
end